apiVersion: apps/v1
kind: Deployment
metadata:
  name: arkadocs
  namespace: arkadocs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: arkadocs
  template:
    metadata:
      labels:
        app: arkadocs
    spec:
      restartPolicy: Always
      containers:
        - name: arkadocs
          image: git.hackos.dev/sreearka/arkadocs:0.1.4
          env:
            - name: DB_URL
              value: "postgres://arkadocs:arkadocs123@postgres-service:5432/arkadocs?sslmode=disable"
---
apiVersion: v1
kind: Service
metadata:
  name: arkadocs
  namespace: arkadocs
spec:
  selector:
    app: arkadocs
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
      cert-manager.io/cluster-issuer: letsencrypt
  name: arkadocs-ingress
  namespace: arkadocs
spec:
  rules:
    - host: docs.sreearkagreentech.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: arkadocs
                port:
                  number: 8000