apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: arka-wp
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  syncPolicy:
    automated: {}
  destination:
    namespace: arka-wp
    server: {{ .Values.spec.destination.server }}
  project: default
  sources:
  - repoURL: registry-1.docker.io/bitnamicharts
    chart: wordpress
    targetRevision: 24.0.7
    helm:
      valueFiles:
      - $values/arka-wp/values.yaml
  - repoURL: 'https://github.com/HackedOS/kube'
    targetRevision: main
    ref: values