apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: forgejo
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  syncPolicy:
    automated: 
      prune: true
  destination:
    namespace: forgejo
    server: {{ .Values.spec.destination.server }}
  project: default
  sources:
  - repoURL: code.forgejo.org/forgejo-helm
    chart: forgejo
    targetRevision: 7.0.0
    helm:
      valueFiles:
      - $values/forgejo/values.yaml
  - repoURL: 'https://github.com/HackedOS/kube'
    targetRevision: main
    ref: values
  - repoURL: 'https://github.com/HackedOS/kube'
    path: forgejo
    targetRevision: main
    directory:
      exclude: "values.yaml"
