apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: safe
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  syncPolicy:
    automated: 
      prune: true
  destination:
    namespace: safe
    server: {{ .Values.spec.destination.server }}
  project: default
  sources:
  - repoURL: 'https://github.com/HackedOS/kube'
    path: safe
    targetRevision: main