apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sealed-secrets
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  syncPolicy:
    automated: {}
  destination:
    namespace: kube-system
    server: {{ .Values.spec.destination.server }}
  project: default
  sources:
  - repoURL: https://bitnami-labs.github.io/sealed-secrets
    chart: sealed-secrets
    targetRevision: 2.15.4
    helm:
      releaseName: sealed-secrets
      valuesObject:
        fullnameOverride: "sealed-secrets-controller"
