runner:
  config:
    instance: 'http://forgejo-http.forgejo.svc.cluster.local:3000'
    name: 'k3s-runner'
    token: 'yUIcjpXR9l0zhrutwdO4Oh6yxOqi6xguTI985FyQ'
    file:
      runner:
        capacity: 4
        envs:
          A_TEST_ENV_NAME_1: null
          A_TEST_ENV_NAME_2: null
          DOCKER_HOST: tcp://127.0.0.1:2376
          DOCKER_TLS_VERIFY: 1
          DOCKER_CERT_PATH: /certs/client
      container:
        network: host
        options: -v /certs/client:/certs/client
        valid_volumes:
          - /certs/client