apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: runner-secret
  namespace: forgejo
spec:
  encryptedData:
    token: AgCehvJMSLxyunC9+OydwneuPTI4qmjbKRse6u3g0td1FSvIg8BnHyHkZmMjLPgvZ5MPurxgMdRs/o9RKhQHGJfLE5ZZSTXuZYoMaOePRpH0PJHO14faZTT2wdn6lmwl4kkqY830h3F2PMNv1wDGd3W35LjGjS3ULL0WL00tvDGNWnRAKgPFfjww4GdDvHN3H3Uv/TdeKTZtuTfeaxWmm09Ln7qtrTYcIU3ZkDK4ImgV1IrqWYo59zgNJnwB4y46NkbrL0yQI4O/WPqZ2Fao/EszZy9ZmK68X9ENyxSVUy8IfJZNXWrIoWLbedwhP/1ns02uLuiOaft88aFLMg9pn5SbFwbE19a/B4NDokwU0bjIGvIMhOIJ6OShZV1D0hD+Uk836jrZjNhqu6k41XIuMSYgiMMcLuoZJ+T2um0IB5fEW/QAsRwpcFtajOogzZ12CQunFB8Nf1eRnUqkvI5yAD96Y02xT0hwoiXDDFrp9ZPxMr0EevqJxUnF+H5rWSHd1qgTsHAS/0rZa5QjWJc4yNc+mCLmMWSqqY5Y4ck5EuuoFzJkeJoYrYGuzovZ1XFlQucXxvgse1eWghlnEvnXEhRi3fAUh7jzt6R1kHOdCOSVMW1DBPqmo7NqSknC0lo7l0NxnmUyShxu5seMGo39VCvdGkHMtwJHmDo1IUVmEL5Hrpn5eYjFztYFIe7JTZXciZbSUPoVgWmOaQHOF2hxHkElpR/FiFUtWtcvPHm68OXuaiXRBVmp3QSa