apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: runner-secret
  namespace: forgejo
spec:
  encryptedData:
    token: AgCdfDOE3V9SFXw8MkwE1XhxMe008VRXI2VnjS7SJQ8lDof8Gqvw1iHocEXESGpri4tQKrSyFv1J/vD5tYLpUkO4yV45z9eONwXds0hwLeBRvTKc1m2F1yBpuTa6NWW/gWwvuu0AK9h1A4IoTbtmKrOJpP6054B03eI6/6+65QLMjNXwOHVAd9HR6ypu8FVfhm9v/DLRneYf8cFcqIxVzf5jtycl8yJtCzUM2NwW/Iw8KmydQ2mwzyuHscBmeynjjMakDYftDqkslrl7Nbjt8KvnKNx7UUcSXj9JPoLUowPWkMxcZWEpXQQQhuQiA4y3mHprv6m+zWLniYUtbd/TUrmCiWZWICYJqFgkoxXoAXGkobu30hGroHoYO8xfChHI4+s2ay8AKd1z85Ta8pTONWlnL4U/H0KpXcO0giczGK0ad1pKyKDquomJIHbTxwjvZme5WXGI6Z9ND66sY5Q7fZApQ9CUsiiOu/NIb2R3AWSEXuwCUUkEd57M6fKwDzRLyo9k9Qv7b+BUY3QePyYDB35OiCXhkvrogEfdq2g1NTlfN4d+bS2cNZd0bHV5Z/eh+qebKWI7g/uMB+Js2aJmcpQp8zz+haD6LiES+dW3EigJ9TkmeZaaCQ1cB3pxKC/fzPnOzopdd0VH8RtXfHUEqdZ843UZ7HallQpoHkQA/xW/Cjt7t3lm8vSr4Fd5J27xNHpbz11JSXAEyDkoDqFQf1MjeiT7Gx2V7hZ9GYibWEiVJQswJ8mfRl04