gitea:
  config:
    APP_NAME: "Hack's Computer Kitchen"
    actions: 
      ENABLED: true

ingress:
  enabled: true
  className:
  annotations:
    {}
  hosts:
    - host: git.hackos.dev
      paths:
        - path: /
          pathType: Prefix
  tls: []

postgresql:
  enabled: true

postgresql-ha:
  enabled: false

redis-cluster:
  enabled: false