apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: microbin-data
  namespace: microbin
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: microbin
  namespace: microbin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: microbin
  template:
    metadata:
      labels:
        app: microbin
    spec:
      restartPolicy: Always
      containers:
        - name: microbin
          image: danielszabo99/microbin:2.0.4
          env:
            - name: MICROBIN_PORT
              value: "8080"
            - name: MICROBIN_ADMIN_USERNAME
              valueFrom:
                  secretKeyRef:
                    name: microbin-secret
                    key: MICROBIN_ADMIN_USERNAME
            - name: MICROBIN_ADMIN_PASSWORD
              valueFrom:
                  secretKeyRef:
                    name: microbin-secret
                    key: MICROBIN_ADMIN_PASSWORD
            - name: MICROBIN_FOOTER_TEXT
              value: "hack's shared bin service - powered by microbin"
            - name: MICROBIN_PUBLIC_PATH
              value: "https://bin.hackos.dev"
            - name: MICROBIN_MAX_FILE_SIZE_UNENCRYPTED_MB
              value: "6144"
            - name: MICROBIN_MAX_FILE_SIZE_ENCRYPTED_MB
              value: "6144"
            - name: MICROBIN_DISABLE_TELEMETRY
              value: "true"
          volumeMounts:
            - name: microbin-data
              mountPath: /app/microbin_data
      volumes:
        - name: microbin-data
          persistentVolumeClaim:
            claimName: microbin-data
---
apiVersion: v1
kind: Service
metadata:
  name: microbin
  namespace: microbin
spec:
  selector:
    app: microbin
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
      cert-manager.io/cluster-issuer: letsencrypt
  name: microbin-ingress
  namespace: microbin
spec:
  rules:
    - host: bin.hackos.dev
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: microbin
                port:
                  number: 8080