apiVersion: v1
kind: ConfigMap
metadata:
  name: headscale-config
  namespace: headscale
data:
  config.yaml: |
    server_url: https://hail.hackos.dev
    listen_addr: 0.0.0.0:8080
    noise:
      private_key_path: /var/lib/headscale/noise_private.key
    prefixes:
      v6: fd7a:115c:a1e0::/48
      v4: 100.64.0.0/10
      allocation: sequential
    database:
      type: sqlite
      sqlite:
        path: /var/lib/headscale/db.sqlite
    dns:
      nameservers.global:
        - 1.1.1.1
      magic_dns: true
      base_domain: hackos.tail
    derp:
      urls:
        - https://controlplane.tailscale.com/derpmap/default