apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: headscale-data
  namespace: headscale
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 128Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: headscale
  namespace: headscale
spec:
  replicas: 1
  selector:
    matchLabels:
      app: headscale
  template:
    metadata:
      labels:
        app: headscale
    spec:
      restartPolicy: Always
      containers:
        - name: headscale
          image: headscale/headscale:0.23.0-alpha12
          command: ["headscale", "serve"]
          volumeMounts:
            - name: headscale-data
              mountPath: /var/lib/headscale/
            - name: headscale-config
              mountPath: /etc/headscale/
      volumes:
        - name: headscale-data
          persistentVolumeClaim:
            claimName: headscale-data
        - name: headscale-config
          configMap:
            name: headscale-config
---
apiVersion: v1
kind: Service
metadata:
  name: headscale
  namespace: headscale
spec:
  selector:
    app: headscale
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080